"""
Static marketplace products for demo purposes
"""

STATIC_PRODUCTS = [
    {
        "id": 1001,
        "title": "iPhone 14 Pro",
        "brand": "Apple",
        "model": "A2894",
        "description": "Latest iPhone with Pro camera system",
        "price": 74999,
        "original_price": 91999,
        "category_id": 1,
        "images": ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=400&h=400&fit=crop"],
        "specifications": {"Storage": "128GB", "RAM": "6GB", "Display": "6.1 inch"},
        "warranty_info": "1 year Apple warranty",
        "seller_name": "TechStore",
        "seller_rating": 4.8,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1002,
        "title": "Samsung Galaxy S23",
        "brand": "Samsung", 
        "model": "SM-S911",
        "description": "Flagship Android phone with excellent camera",
        "price": 58499,
        "original_price": 75299,
        "category_id": 1,
        "images": ["https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=400&h=400&fit=crop"],
        "specifications": {"Storage": "256GB", "RAM": "8GB", "Display": "6.1 inch"},
        "warranty_info": "2 year Samsung warranty",
        "seller_name": "MobileHub",
        "seller_rating": 4.6,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1003,
        "title": "MacBook Pro 14",
        "brand": "Apple",
        "model": "M2",
        "description": "Professional laptop with M2 chip",
        "price": 158999,
        "original_price": 184999,
        "category_id": 2,
        "images": ["https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop"],
        "specifications": {"Processor": "M2 Pro", "RAM": "16GB", "Storage": "512GB SSD"},
        "warranty_info": "1 year Apple warranty",
        "seller_name": "AppleStore",
        "seller_rating": 4.9,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1004,
        "title": "Dell XPS 13",
        "brand": "Dell",
        "model": "9320",
        "description": "Ultra-portable Windows laptop",
        "price": 99999,
        "original_price": 116999,
        "category_id": 2,
        "images": ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=400&fit=crop"],
        "specifications": {"Processor": "Intel i7", "RAM": "16GB", "Storage": "512GB SSD"},
        "warranty_info": "2 year Dell warranty",
        "seller_name": "DellDirect",
        "seller_rating": 4.5,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1005,
        "title": "Samsung 4K Smart TV",
        "brand": "Samsung",
        "model": "QN55Q80C",
        "description": "55-inch QLED 4K Smart TV",
        "price": 108999,
        "original_price": 133999,
        "category_id": 3,
        "images": ["https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop"],
        "specifications": {"Size": "55 inch", "Resolution": "4K QLED", "Smart TV": "Yes"},
        "warranty_info": "3 year Samsung warranty",
        "seller_name": "ElectroWorld",
        "seller_rating": 4.7,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1006,
        "title": "PlayStation 5",
        "brand": "Sony",
        "model": "CFI-1215A",
        "description": "Next-gen gaming console",
        "price": 49999,
        "original_price": 49999,
        "category_id": 5,
        "images": ["https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=400&fit=crop"],
        "specifications": {"Storage": "825GB SSD", "RAM": "16GB GDDR6", "GPU": "Custom RDNA 2"},
        "warranty_info": "1 year Sony warranty",
        "seller_name": "GameZone",
        "seller_rating": 4.8,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1007,
        "title": "Sony WH-1000XM5",
        "brand": "Sony",
        "model": "WH1000XM5",
        "description": "Noise canceling wireless headphones",
        "price": 24999,
        "original_price": 33499,
        "category_id": 4,
        "images": ["https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop"],
        "specifications": {"Type": "Over-ear", "Battery": "30 hours", "Noise Canceling": "Yes"},
        "warranty_info": "1 year Sony warranty",
        "seller_name": "AudioTech",
        "seller_rating": 4.9,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1008,
        "title": "iPad Pro 12.9",
        "brand": "Apple",
        "model": "M2",
        "description": "Professional tablet with M2 chip",
        "price": 91999,
        "original_price": 108999,
        "category_id": 6,
        "images": ["https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop"],
        "specifications": {"Display": "12.9 inch", "Storage": "256GB", "Processor": "M2"},
        "warranty_info": "1 year Apple warranty",
        "seller_name": "AppleStore",
        "seller_rating": 4.8,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1009,
        "title": "AirPods Pro 2",
        "brand": "Apple",
        "model": "MTJV3",
        "description": "Active Noise Cancellation earbuds",
        "price": 16699,
        "original_price": 20899,
        "category_id": 4,
        "images": ["https://images.unsplash.com/photo-1606220945770-b5b6c2c55bf1?w=400&h=400&fit=crop"],
        "specifications": {"Type": "True wireless", "Battery": "6 hours", "Noise Canceling": "Active"},
        "warranty_info": "1 year Apple warranty",
        "seller_name": "AppleStore",
        "seller_rating": 4.8,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1010,
        "title": "Nintendo Switch OLED",
        "brand": "Nintendo",
        "model": "HEG-001",
        "description": "Portable gaming console with OLED screen",
        "price": 29299,
        "original_price": 29299,
        "category_id": 5,
        "images": ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=400&fit=crop"],
        "specifications": {"Display": "7 inch OLED", "Storage": "64GB", "Battery": "4.5-9 hours"},
        "warranty_info": "1 year Nintendo warranty",
        "seller_name": "GameZone",
        "seller_rating": 4.7,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1011,
        "title": "LG OLED TV 65",
        "brand": "LG",
        "model": "OLED65C3",
        "description": "65-inch OLED TV with perfect blacks",
        "price": 167499,
        "original_price": 209299,
        "category_id": 3,
        "images": ["https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=400&h=400&fit=crop"],
        "specifications": {"Size": "65 inch", "Resolution": "4K OLED", "HDR": "Dolby Vision"},
        "warranty_info": "2 year LG warranty",
        "seller_name": "LG Official",
        "seller_rating": 4.8,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1012,
        "title": "Google Pixel 7 Pro",
        "brand": "Google",
        "model": "GVU6C",
        "description": "Pure Android with advanced AI camera",
        "price": 45999,
        "original_price": 75299,
        "category_id": 1,
        "images": ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop"],
        "specifications": {"Storage": "128GB", "RAM": "12GB", "Camera": "50MP main"},
        "warranty_info": "1 year Google warranty",
        "seller_name": "PixelStore",
        "seller_rating": 4.7,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1013,
        "title": "Xbox Series X",
        "brand": "Microsoft",
        "model": "RRT-00001",
        "description": "Most powerful Xbox with 4K gaming",
        "price": 37699,
        "original_price": 41899,
        "category_id": 5,
        "images": ["https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=400&h=400&fit=crop"],
        "specifications": {"Storage": "1TB SSD", "RAM": "16GB", "GPU": "Custom RDNA 2"},
        "warranty_info": "1 year Microsoft warranty",
        "seller_name": "XboxStore",
        "seller_rating": 4.7,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1014,
        "title": "ASUS ROG Gaming Laptop",
        "brand": "ASUS",
        "model": "GA402RJ",
        "description": "Gaming laptop with RTX 3060",
        "price": 108999,
        "original_price": 150699,
        "category_id": 2,
        "images": ["https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=400&h=400&fit=crop"],
        "specifications": {"Processor": "AMD Ryzen 9", "RAM": "16GB", "GPU": "RTX 3060"},
        "warranty_info": "2 year ASUS warranty",
        "seller_name": "GamerHub",
        "seller_rating": 4.6,
        "is_selling": True,
        "status": "available"
    },
    {
        "id": 1015,
        "title": "Logitech MX Master 3S",
        "brand": "Logitech",
        "model": "910-006556",
        "description": "Advanced wireless mouse",
        "price": 6699,
        "original_price": 8399,
        "category_id": 6,
        "images": ["https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=400&fit=crop"],
        "specifications": {"Type": "Wireless", "Battery": "70 days", "DPI": "8000"},
        "warranty_info": "2 year Logitech warranty",
        "seller_name": "TechAccessories",
        "seller_rating": 4.6,
        "is_selling": True,
        "status": "available"
    }
]